// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgrlvodoufjudnnhlfmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indncmx2b2RvdWZqdWRubmhsZm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjk4NzIsImV4cCI6MjA2MzkwNTg3Mn0.nyJXD9JzsAIR1b_VBZHDx--ZuoBldvLz0mDvHUX62dU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);